"use client";
//import type { Metadata } from "next";
import '@/styles/globals.css'
import { Provider } from "react-redux";
import store from "@/store/index";
import React from "react"; // Ensure this import exists

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Provider store={store}>{children}</Provider>
      </body>
    </html>
  );
}
